// @ts-check
/** Ability cooldowns, energy pools, and active effect instances. */

/**
 * @param {Document | null | undefined} [doc]
 * @returns {import('../../types/game-state.js').AbilityState}
 */
export function createAbilityState(doc) {
    const root = doc ?? (typeof document !== 'undefined' ? document : null);
    /** @param {string} id @returns {HTMLElement | null} */
    const el = (id) => root?.getElementById(id) ?? null;
    return {
        holoDuration: 3000,
        holoCooldown: 5000,
        lastHoloTime: 0,
        activeBombs: [],
        lastBombTime: 0,
        bombCooldown: 5000,
        activeMissiles: [],
        lastMissileTime: 0,
        missileCooldown: 1500,
        activeBlackHoles: [],
        lastBlackHoleTime: 0,
        blackHoleCooldown: 5000,
        lastSizeShiftTime: 0,
        sizeShiftCooldown: 1000,
        shieldEnergy: 100,
        maxShieldEnergy: 100,
        shieldActive: false,
        lastTeleportTime: 0,
        teleportCooldown: 5000,
        teleportDistance: 15.0,
        lastBlinkTime: 0,
        blinkCooldown: 2000,
        gliderEnergy: 100,
        maxGliderEnergy: 100,
        gliderActive: false,
        buildEnergy: 100,
        maxBuildEnergy: 100,
        timeScale: 1.0,
        focusEnergy: 100,
        maxFocusEnergy: 100,
        focusActive: false,
        hoverEnergy: 100,
        maxHoverEnergy: 100,
        hoverActive: false,
        jetpackEnergy: 100,
        maxJetpackEnergy: 100,
        jetpackActive: false,
        iceEnergy: 100,
        maxIceEnergy: 100,
        lastIceTime: 0,
        iceCooldown: 150,
        iceActive: false,
        phaseEnergy: 100,
        maxPhaseEnergy: 100,
        phaseActive: false,
        flipEnergy: 100,
        maxFlipEnergy: 100,
        flipActive: false,
        vortexEnergy: 100,
        maxVortexEnergy: 100,
        vortexActive: false,
        empEnergy: 100,
        maxEmpEnergy: 100,
        empActive: false,
        lastEmpTime: 0,
        empCooldown: 3000,
        lastTremorTime: 0,
        tremorCooldown: 5000,
        tremorShakeTimer: 0,
        violetEnergy: 100,
        maxVioletEnergy: 100,
        violetActive: false,
        violetLightEntity: null,
        timeStopEnergy: 100,
        maxTimeStopEnergy: 100,
        timeStopActive: false,
        timeStopSavedStates: new Map(),
        chameleonState: 0,
        lastChameleonTime: 0,
        chameleonCooldown: 1000,
        chameleonProfiles: [
            { name: 'Normal', color: [1, 1, 1], gravityScale: 1.0 },
            { name: 'Heavy', color: [0.2, 0.2, 0.2], gravityScale: 2.5 },
            { name: 'Bouncy', color: [1, 0.2, 0.8], gravityScale: 0.5 },
            { name: 'Floaty', color: [0.2, 0.8, 1.0], gravityScale: 0.1 },
        ],
        adrenaline: 0,
        maxAdrenaline: 100,
        isRewinding: false,
        maxRewindFrames: 300,
        _rewindBuffer: new Float32Array(300 * 13),
        _rewindHead: 0,
        _rewindCount: 0,
        gravityPulseCooldown: 5000,
        lastGravityPulseTime: 0,
        holobarEl: el('holobar'),
        holobarContainerEl: el('holobar-container'),
        bombBarEl: el('bombbar'),
        bombBarContainerEl: el('bombbar-container'),
        missileBarEl: el('missilebar'),
        missileBarContainerEl: el('missilebar-container'),
        blackHoleBarEl: el('blackholebar'),
        blackHoleBarContainerEl: el('blackholebar-container'),
        sizebarEl: el('sizebar'),
        sizebarContainerEl: el('sizebar-container'),
        shieldbarEl: el('shieldbar'),
        shieldbarContainerEl: el('shieldbar-container'),
        blinkBarEl: el('blinkbar'),
        blinkBarContainerEl: el('blinkbar-container'),
        teleportBarEl: el('teleportbar'),
        teleportBarContainerEl: el('teleportbar-container'),
        gliderBarEl: el('gliderbar'),
        gliderBarContainerEl: el('gliderbar-container'),
        chameleonBarEl: el('chameleonbar'),
        chameleonBarContainerEl: el('chameleonbar-container'),
        hoverBarEl: el('hoverbar'),
        hoverBarContainerEl: el('hoverbar-container'),
        buildbarEl: el('buildbar'),
        buildbarContainerEl: el('buildbar-container'),
        jetpackbarEl: el('jetpackbar'),
        jetpackbarContainerEl: el('jetpackbar-container'),
        icebarEl: el('icebar'),
        icebarContainerEl: el('icebar-container'),
        phasebarEl: el('phasebar'),
        phasebarContainerEl: el('phasebar-container'),
        flipbarEl: el('flipbar'),
        flipbarContainerEl: el('flipbar-container'),
        vortexbarEl: el('vortexbar'),
        vortexbarContainerEl: el('vortexbar-container'),
        empBarEl: el('empbar'),
        empBarContainerEl: el('empbar-container'),
        groundslambarEl: el('groundslambar'),
        groundslambarContainerEl: el('groundslambar-container'),
        violetbarEl: el('violetbar'),
        violetbarContainerEl: el('violetbar-container'),
        timeStopbarEl: el('timestopbar'),
        timeStopbarContainerEl: el('timestopbar-container'),
        adrenalineBarEl: el('adrenalinebar'),
        adrenalineBarContainerEl: el('adrenalinebar-container'),
        gravityPulseBarEl: el('gravitypulsebar'),
        gravityPulseBarContainerEl: el('gravitypulsebar-container'),
    };
}
