// @ts-check
/** Physics bodies, world objects, grapple, magnet, trick tracking. */

/** @returns {import('../../types/game-state.js').PhysicsState} */
export function createPhysicsState() {
    return {
        marbles: [],
        staticBodies: [],
        staticEntities: [],
        dynamicObjects: [],
        dynamicBodies: new Set(),
        checkpoints: [],
        collectibles: [],
        collectibleRotation: 0,
        powerUps: [],
        powerUpRotation: 0,
        activeEffects: { speed: 0, jump: 0 },
        movingPlatforms: [],
        rotatingPlatforms: [],
        temporaryPlatforms: [],
        playerMarble: null,
        visualParticles: [],
        trickState: {
            airTime: 0,
            spin: 0,
            wallRides: 0,
            highSpeed: 0,
            flips: 0,
            rolls: 0,
            wallBounces: 0,
            maxAltitude: 0,
            startAltitude: 0,
        },
        isWallRiding: false,
        wallRideTime: 0,
        isStomping: false,
        stompStartTime: 0,
        magnetPower: 1.0,
        magnetActive: false,
        magnetMode: null,
        grappleAnchors: [],
        isGrappling: false,
        grappleTarget: null,
        grappleEntity: null,
        grappleInst: null,
        grappleMaxDist: 50.0,
        grappleForce: 40.0,
        isGrappleZipping: false,
        portalA: null,
        portalB: null,
        lastPortalTeleportTime: 0,
        portalCooldown: 500,
        nearMisses: new Map(),
    };
}
