export const marbleDraft = [
    {
        name: "Celestial Pearl",
        color: [0.95, 0.9, 1.0],
        offset: { x: 0.0, y: 5, z: 0 },
        radius: 0.65,
        density: 1.2,
        restitution: 0.95,
        gravityScale: 0.8,
        friction: 0.05,
        roughness: 0.1,
        emissive: true,
        lightIntensity: 45000.0,
        lightColor: [0.8, 0.9, 1.0]
    },
    {
        name: "Celestial Orb",
        color: [0.3, 0.7, 1.0],
        offset: { x: 0.0, y: 5, z: 0 },
        radius: 0.6,
        density: 1.5,
        restitution: 0.8,
        gravityScale: 0.8,
        friction: 0.1,
        roughness: 0.05,
        emissive: true,
        lightIntensity: 30000.0,
        lightColor: [0.5, 0.0, 1.0]
    },
    {
        name: "Abyssal Eye",
        color: [0.1, 0.0, 0.2],
        offset: { x: 0.0, y: 5, z: 0 },
        radius: 0.55,
        density: 5.0,
        restitution: 0.2,
        gravityScale: 1.5,
        friction: 0.8,
        roughness: 0.0,
        emissive: true,
        lightIntensity: 60000.0,
        lightColor: [0.3, 0.0, 0.8]
    },
    {
        name: "Void Walker",
        color: [0.1, 0.1, 0.1],
        offset: { x: 0.0, y: 5, z: 5 },
        radius: 0.5,
        density: 0.5,
        restitution: 0.8,
        gravityScale: 0.3,
        friction: 0.1,
        roughness: 0.9,
        emissive: true,
        lightIntensity: 20000.0,
        lightColor: [0.5, 0.0, 1.0]
    },
    {
        name: "Astral Jumper",
        color: [0.0, 0.5, 1.0],
        offset: { x: 0.0, y: 5, z: 10 },
        radius: 0.5,
        density: 1.0,
        restitution: 1.5,
        gravityScale: 0.4,
        friction: 0.1,
        roughness: 0.0,
        emissive: true,
        lightIntensity: 35000.0,
        lightColor: [0.0, 0.5, 1.0]
    }
];
